### ISSUE TITLE
Where to find the Linting Outputs

### ISSUE THREAD

**Issue by yaacine** [kitek/dartanalyzer-annotations-action#4]
I used this action in my pipeline for pull request and it's working as shown in the pictures below , but I am unable to find the output anywhere. So my question is: where I am supposed to find the output of this linting please ?

<img width="649" alt="Screen Shot 2020-09-11 at 9 57 26 AM" src="https://user-images.githubusercontent.com/32752884/92897301-fe3aa180-f414-11ea-99e2-24f661339a7c.png">

<img width="920" alt="Screen Shot 2020-09-11 at 9 54 30 AM" src="https://user-images.githubusercontent.com/32752884/92896979-bb78c980-f414-11ea-889f-151bf0cb4dc2.png">

**Comment by kitek** [comment]
If the check fails output should be visible on the "Files changed" tab in your Pull Request.
I've just made an example of PR with a failed check here: https://github.com/kitek/flutter-kradio-player/pull/22/files

**Comment by yaacine** [comment]
@kitek  thanks a lot for your answer , it's working very well now 🚀
